#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/foodapplication
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    hibernate:
#      naming:
#        physical-strategy: com.learning.utils.CustomNamingStrategy
#      ddl-auto: update
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#server:
#  port: 9005
#  servlet:
#    context-path: /api


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodapplications
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.learning.utils.CustomNamingStrategy
      ddl-auto: update
server:
  port: 9005
learning:
  app:
    jwtSecret: secretKey
    jwtExpirationMs: 86400000